import Head from "next/head";
import { Inter } from "next/font/google";
import React, { useState, useEffect, useRef } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>FORM PENGGANDAAN MEDALI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="glocolis-section">
        <div className="container">
          <div className="content">
            <h1 className="sub">FORMULIR PENGGANDAAN MEDALI</h1>
            {/* <h1 className="garis-bawah"></h1> */}
            <br></br>

            <div className="info">
              <p>
                Pilih salah satu dari beberapa nama acara event yang sedang
                diikuti dan di mana anda ingin melakukan penggandaan jumlah
                medali yang diperoleh...
              </p>
            </div>
            <form name="regist-form mt-5">
              <div class="link-web mx-auto text-center">
                {/* <Link href="/event/glocolis" legacyBehavior>
                  <a className="btn btn--primary text-center mt-5">
                    Penggandaan GLOCOLIS
                  </a>
                </Link>
                <Link href="/event/ispc" legacyBehavior>
                  <a class="btn btn--accent text-center mt-5">
                    Penggandaan ISPC
                  </a>
                </Link> */}
                <Link href="/event/wice" legacyBehavior>
                  <a className="btn btn--primary text-center mt-5">
                    Penggandaan  WICE
                  </a>
                </Link>
                <Link href="/event/nice" legacyBehavior>
                  <a className="btn btn--primary text-center mt-5">
                    Penggandaan NICE
                  </a>
                </Link>
              </div>
            </form>
          </div>
        </div>
      </section>
    </>
  );
}
